package com.tc.nearanddear.model

import androidx.navigation.Navigator
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class LoginUser(
    val id: Long? = null, // optional, auto-generated by Supabase
    val created_at: String? = null, // optional, auto-managed by Supabase
    val name: String,
    val email: String,
    val avatar_url: String,
    var location_model: LocationModel?,
    val userID: String,
    @SerialName("updated_at") val updated_at: String,
    val friendList: List<FriendModel>? = emptyList() // fix here

)

@Serializable
data class LoginUserLite(
    val name: String, val location_model: LocationModel
)

@Serializable
data class LocationModel(
    val latitude: Double, val longitude: Double
)

@Serializable
data class FriendModel(
    val name: String,
    val userID: String,
    var friendState: FriendState
)

@Serializable
enum class FriendState {
    @SerialName("FRIEND")
    FRIEND,

    @SerialName("REQUEST")
    REQUEST,

    @SerialName("PENDING")
    PENDING
}

@Serializable
data class SearchResult(
    val name: String, val userID: String, val avatar_url: String
)

