package com.tc.nearanddear.model

import kotlinx.serialization.Serializable

@Serializable
data class LoginUser(
    val id: Long? = null, // optional, auto-generated by Supabase
    val created_at: String? = null, // optional, auto-managed by Supabase
    val name: String,
    val email: String,
    val avatar_url: String,
    val location_model: LocationModel?,
    val userID: String,
    val updated_at: String,
    val friendList: List<FriendModel>? = emptyList() // fix here
)

@Serializable
data class LocationModel(
    val latitude: Double,
    val longitude: Double
)

@Serializable
data class FriendModel(
    val userID: String,
    val userName: String,
    val friendState: FriendState
)

@Serializable
enum class FriendState {
    FRIEND,
    REQUEST,
    PENDING
}

